### ISSUE TITLE
I would like to be able to select the "search" page for an environment

### ISSUE THREAD

**Issue by tguilpain** [vbouchet31/alfred-acquia-cloud-shortcuts#1]
When i select an environment, I only see 7 options.
In cloud UI I see 12
Is it possible to add more options with a local override? Or where should I look in the code the change this?

![image](https://user-images.githubusercontent.com/1541667/158191794-f893a23a-e830-4d63-9033-2aaa23cf8b1f.png)

**Comment by tguilpain** [comment]
do I just need to add in the following array ? -> https://github.com/vbouchet31/alfred-acquia-cloud-shortcuts/blob/06db00db778cd4eface67f61ec7d24d83c20fe67/index.js#L80

**Comment by vbouchet31** [comment]
Yes. Nothing fancy to automatically discover the tabs ;-)

**Comment by tguilpain** [comment]
Thanks :)
